# create docker compose file
name: app
services:
  app:
    image: topsetting4571/simple-apps
    build: ./app
    ports:
      - "5000:3000"
    volumes:
      - vol-simple:/app/public/images

volumes:
  vol-simple: